apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gateway-deployment.yaml
- booking-deployment.yaml
- event-deployment.yaml
- discount-deployment.yaml
- itm-ingress.yaml
- gateway-hpa.yaml
- booking-hpa.yaml
- event-hpa.yaml
- discount-hpa.yaml

secretGenerator:
- name: itm-env
  envs:
  - .env

generatorOptions:
  disableNameSuffixHash: true
